### ISSUE TITLE
Missing location field in `DecisionFull`

### ISSUE THREAD

**Issue by alodieboissonnet** [antoinejeannot/jurisprudence#5]
Hello! Thanks for your great work on Judilibre data!
The `DecisionFull` object is missing a `location` field, though this field is given by Judilibre API and is used in the `DecisionLink` object. Would it be possible to add it to `DecisionFull` please? I don't have rights to push a PR to the repo

**Comment by antoinejeannot** [comment]
Hi @alodieboissonnet, thanks for your kind words! 
Have you tried forking this repo, creating a branch then opening a PR ?
The `location` subfield is optional and stored in nested fields from `DecisionFull`, not `DecisionFull` directly:
- contested
- timeline
- rapprochements
- forward
I checked `schema.py` and it seems handled.
Feel free to add examples or open a PR so that I can help you investigate!


see https://raw.githubusercontent.com/Cour-de-cassation/judilibre-search/master/public/JUDILIBRE-public.json for reference

**Comment by alodieboissonnet** [comment]
Hi @antoinejeannot! Thanks for your quick answer

I managed to create a PR by forking the repo actually, thanks! I'd be happy to get a review from you on my PR: https://github.com/antoinejeannot/jurisprudence/pull/6

The `location` field is missing in the API output if it is empty. Though, if it is not empty, Judilibre API returns this field (see example in my PR).

**Comment by antoinejeannot** [comment]
hi @alodieboissonnet thanks a lot for your contribution!
You were :100: right, it seems like the OpenAPI schema is not updated on Judilibre's side.
There might have some other minor issues as well due to this deprecated schema issue.
I will reach out to Judilibre's maintainers :)
In the meantime, I will run the export script tonight so that you will be able to make progress with the `location` field by tomorrow!
Thanks again for helping improve the French justice.

**Comment by alodieboissonnet** [comment]
Thanks a lot @antoinejeannot for your help and reactivity, your work on Judilibre is very useful!
